#!/bin/sh

set UNAME=discodj-kiosk
set BACKUP=/home/$UNAME/backup

adduser --disabled-password --quiet $UNAME

# Backup the bits that will be overwritten
mkdir $BACKUP
cp /etc/default/hostapd $BACKUP
cp /etc/hostapd/hostapd.conf $BACKUP
cp /etc/network/interfaces $BACKUP
cp /etc/inittab $BACKUP
