#!/bin/sh

BACKUP=/usr/share/discodj-kiosk/backup

# Backup the bits that will be overwritten
mkdir -p $BACKUP
cp /etc/default/hostapd $BACKUP
cp /etc/hostapd/hostapd.conf $BACKUP
cp /etc/network/interfaces $BACKUP
cp /etc/inittab $BACKUP
