#! /bin/sh
### BEGIN INIT INFO
# Provides:          discodj
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DiscoDJ
# Description:       This script starts and stops the DiscoDJ process. DiscoDJ
#                    is a simple application for a requests based playlist
#                    suited for wedding DJ type scenarios.
### END INIT INFO

CLASS_PATH=/usr/share/discodj/discodj.jar:/etc/discodj
for jar in `ls /usr/share/discodj/lib`
do
  CLASS_PATH=$CLASS_PATH:/usr/share/discodj/lib/$jar
done

JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="DiscoDJ server"
NAME=discodj
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/jsvc
DAEMON_ARGS="-outfile /var/log/discodj/jsvc.out.log -errfile /var/log/discodj/jsvc.err.log -user discodj -pidfile $PIDFILE -procname $NAME -home $JAVA_HOME -cp $CLASS_PATH com.totalchange.discodj.web.server.DiscoDjApplication"
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	$DAEMON $DAEMON_ARGS
}

#
# Function that stops the daemon/service
#
do_stop()
{
	$DAEMON -stop $DAEMON_ARGS
	RETVAL="$?"
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	log_end_msg $?
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	log_end_msg $?
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0)
		do_start
		log_end_msg $?
		;;
	  *)
		# Failed to stop
		log_end_msg $?
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
